spring:
  jpa:
    generate-ddl: true

 
---
spring:
  datasource:
    url: "jdbc:sqlserver://xxxxxxxxxxx.database.windows.net:1433;database=custdb;Encrypt=true;TrustServerCertificate=false;HostNameInCertificate=*.database.windows.net;loginTimeout=30"
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    dataSourceProperties.ColumnEncryptionSetting: "Enabled"
    username: xxxxxxxxx
    password: xxxxxxxxx

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect

azure:
  vault: 
    clientId: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    clientSecret: xxxxxxxxxxxxxxxxxxxxxxxxxxxx

 
